### PR TITLE
This fixes the previous PR

### PR DESCRIPTION
**Pull request by sahil-shubham**
This PR would fix the issue with the JS not loading properly

### CODE REVIEW

**Comment by thealphadollar** [comment]
Great, looking forward to the solution. I've added a WIP to the title since this is a work in progress PR, please remove it once you've fixed the issue.

**Comment by sahil-shubham** [comment]
>I've added a WIP to the title since this is a work in progress PR, please remove it once you've fixed the issue.

Okay, sure. 

@thealphadollar I wanted to know how to correctly host the whole application, because a reason why the JS loads on my side could be that I just load the frontend part. From my side I am not able to get any information from the net, as could be seen from this screenshot which I get after clicking on **Download ICS**:
error

**error above:** Cannot GET /templates/%7B%7Burl_for('homepage')%7D%7D

**Comment by thealphadollar** [comment]
> I wanted to know how to correctly host the whole application

Yo Sahil! Thank for you asking and bringing it to my notice; my apologies for incomplete documentation of the same. We use Python, flask, and gunicorn to serve the backend. I've added instructions in the `README.md`.

**Comment by sahil-shubham** [comment]
> I've added instructions in the README.md.

Thank you, I was able to host the whole application. 

In the previous PR, these were the following issues:-
- [x] **the "add to google calendar" wasn't disabled properly** - This problem could have been because "disabled" is not a valid attribute of the anchor tag. Now, I have changed the **enableButton** function so that it adds **href** to enable. Hence, this issue shouldn't arise again.
- [x] **the info regarding ICS wasn't loading properly** - This problem was assumed to be because of improper loading of the js, but I wasn't able to find any issue. But, I was able to reproduce the exact looking error after removing all the css of the classes (**wrap-info** and **learn-more-btn**), this could mean a problem with the css but I wasn't able to find that either except that with a final semicolon (which shouldn't be a problem). Hence this problem remains unsolved.

This is all I did, but don't know how to proceed further. I am not able to get the same problems we did after merging the PR, even after hosting the whole application.

Here is the screenshot of what second error looks like(this is after removing the css):- 
second_error

**Comment by thealphadollar** [comment]
@sahil-shubham Thank you for giving me insights into why the display of hints at the bottom could be disabled. I investigated and found out that it was due to loading of the old cached CSS file. I've fixed it by renaming the file and merged your changes. Thanks a lot <3 Looking forward to more contributions. If you wish to learn more about the caching issue, [this is a good article](https://medium.com/@codebyamir/a-web-developers-guide-to-browser-caching-cc41f3b73e7c) to start with.

I've also made some sanitation changes to the repository, you can have a look at them in the [commit history](https://github.com/metakgp/gyft-serve/commits/master).

**Comment by sahil-shubham** [comment]
@thealphadollar Thank you, I learned a few new things from your commits and about caching issue.

**Pull request merged**
