### PR TITLE
This adds intructions on homepage & about metakgp (#4) fixes #3 fixes #1

### LINKED ISSUE #1: Add More Information About MetaKGP
We should add more branding for Metakgp on the frontend along with adding information regarding how to delete events.

"This is brought to you by Metakgp <3"

The above line can be added at the end.

A link to the original [gyft repo](github.com/metakgp/gyft) should also be included along with adding link "More information regarding adding and deletion of event can be found at GYFT".

### LINKED ISSUE #3: Add More Instructions On The Homepage
Basic information, including but not limited to the following should be added:

- what is an ICS file
- link to how to add ICS to calendar
- how to add ICS to google calendar

### PR DESCRIPTION
**Pull request by sahil-shubham**

### CODE REVIEW

**Review by thealphadollar — CHANGES_REQUESTED** [review]
The code looks great, thanks @sahil-shubham . Would you like to add mobile and desktop screenshots as it would be helpful to me review and merge quickly? You can use chrome's developer tools and feature to view the website in responsive mode.

**Comment by sahil-shubham** [comment]
There is a problem with the transition between the gradient effect of the two divs for smaller desktops and mobiles. As can be seen in the following screenshots: 
mobile_iphoneX

desktop_1280x1024

desktop_1920x1080

I am trying to fix it.

**Review by thealphadollar — APPROVED** [review]
Hey, thanks for making the change so swiftly, really glad you could find the time.  

@sahil-shubham Can you please update the screenshots and then we can merge it :rocket:

**Comment by sahil-shubham** [comment]
screenshot_iphoneX
screenshot_1280x1024
screenshot_1920x1080

**Comment by thealphadollar** [comment]
Thanks @sahil-shubham , I'm merging this now. I'm highly awed by your dedication and efforts towards the contribution. Looking forward to more experiences with you.

**Comment by sahil-shubham** [comment]
Thank you very much for your time. I have looked at some other projects by metakgp and would be looking forward to contriubuting to them. 

Can you please take a look at https://gyft.metakgp.org/ , there seem to some problem with the changes I made. The "add to google calendar" isn't disabled, the more info button is nothing but simple text.

**Comment by thealphadollar** [comment]
@sahil-shubham Thank you for bringing it to my notice, I've reverted it. I think it is probably due to JS not loading - would you like to diagnose the issue? It'll be helpful in learning important diagnosing skills for web development. Please raise a new PR, and if you need any help please comment here.

**Comment by sahil-shubham** [comment]
@thealphadollar Yes, I would like to diagnose the issue myself, I have no experience with it but that is the very reason to do it. 

I have created a new pull  request(#6) and would be discussing this issue there from now on.

**Pull request merged**
